# Exercícios

In [2]:
#Libs usadas no projeto
import math, numpy as np

## 1) Crie uma classe que irá modelar características geométricas de um círculo. Deverá implementar os métodos:
        -> Área 
        -> Perímetro
## Utilize atributos de classe e de instância apropriados. Crie um inicializador e métodos.
$area = \pi*r^2$

$perimetro = 2*\pi*r$

In [3]:
class Circulo:
  def __init__(self, raio):
    self.raio = raio
  
  def calcula_area(self):
    return math.pi * (self.raio ** 2)
  
  def calcula_perimetro(self):
    return (2 * math.pi * self.raio)

circulo = Circulo(raio=1)

print(circulo.calcula_area())
print(circulo.calcula_perimetro())

3.141592653589793
6.283185307179586


## 2) Crie uma classe chamada matemática que conterá duas classes: trigonométrica e algébrica. Defina dentro da classe trigonométrica as seguintes funções:
    -> seno
    -> cosseno
    -> tangente
## Defina dentro da classe algébrica as seguintes funções: 
    -> soma
    -> subtração
    -> multiplicação
    -> divisão
## Cada função deverá receber array e retornar array

In [4]:
class Matematica(object):
  
  def __init__(self, a):
    self.arrayA = a
    
class Trigonometrica(Matematica):

  def seno(self):
    return np.sin(self.arrayA)

  def cosseno(self):
    return np.cos(self.arrayA)

  def tangente(self):
    return np.tan(self.arrayA)

class Algebrica(Matematica):

  def __init__(self, a, b):
    super().__init__(a)
    self.arrayB = b
    
  def soma(self): 
    return np.add(self.arrayA,self.arrayB)

  def subtracao(self): 
    return np.subtract(self.arrayA,self.arrayB)

  def divisao(self): 
    return np.divide(self.arrayA,self.arrayB)

  def multiplicacao(self): 
    return np.multiply(self.arrayA,self.arrayB)


array_trig_a = [2, 4, 8] 
print(f"Valores calculados para Array: {array_trig_a}")

trig = Trigonometrica(array_trig_a)

print(f"Seno {trig.seno()}")
print(f"Cosseno {trig.cosseno()}")
print(f"Tangente {trig.tangente()}")

array_alg_a = [2,4]
array_alg_b = [1,2]
print(f"\nValores calculados: Array A: {array_alg_b}, Array B: {array_alg_b}")

alg = Algebrica(array_alg_a, array_alg_b)

print(f"Soma {alg.soma()}")
print(f"Subtração {alg.subtracao()}")
print(f"Divisão {alg.divisao()}")
print(f"Multiplicação {alg.multiplicacao()}")

Valores calculados para Array: [2, 4, 8]
Seno [ 0.90929743 -0.7568025   0.98935825]
Cosseno [-0.41614684 -0.65364362 -0.14550003]
Tangente [-2.18503986  1.15782128 -6.79971146]

Valores calculados: Array A: [1, 2], Array B: [1, 2]
Soma [3 6]
Subtração [1 2]
Divisão [2. 2.]
Multiplicação [2 8]


## 3) Dados 2 arrays, A e B, remova de A todo elemento pertencente a B

In [5]:
def remove(arrayA, arrayB):
  return np.setdiff1d(arrayA, arrayB)

A = np.array([11,2,4,8,33])
B = np.array([1,2,3,4])

print(f"Valores que pertecem apenas ao array A {remove(A, B)}")

Valores que pertecem apenas ao array A [ 8 11 33]


## 4) Crie uma função que recebe um array, um inteiro n e um inteiro m e que retorne outro array contendo elementos que estão entre os valores n e m do array recebido pela função. 

In [6]:
def retorna_valores_existentes(array,n,m):
  arrarNM = np.arange(n,m)
  mask = np.isin(array,arrarNM)
  return array[mask]
  
array = np.array([-1,8,44,3,7,4,13,6])
n = 2
m = 9
resultado = retorna_valores_existentes(array, n, m)

print(f"Para o array {array} os numeros existentes entre {n} e {m} são: {resultado}")

Para o array [-1  8 44  3  7  4 13  6] os numeros existentes entre 2 e 9 são: [8 3 7 4 6]


## 5) Escreva uma função que recebe um vetor e um inteiro. Compare cada elemento desse vetor com o número inteiro. Se o elemento do vetor for maior, retorne a diferença entre eles, caso contrário, retorne a soma.

In [7]:
def calcula(vetor, inteiro):
  array = np.array(vetor)
  return np.where(array > inteiro, array - inteiro, array + inteiro)

vetor = [1,2,3]
inteiro = 2

print(calcula(vetor, inteiro))

[3 4 1]


## 6) Dada a seguinte matriz:
    -> [ 8,1,7
         4,3,9
         5,2,6]
## escreva uma função que retorne a matriz ordenada por um dos eixos. utilize a função built-in sorted para realizar a ordenação

In [8]:
def quick_sort(matriz):
  arr = np.array(matriz)
  return np.sort(arr)

matrix = [[8,1,7],[4,3,9],[5,2,6]]
print(f"Quick Sort: {quick_sort(matrix)}")

Quick Sort: [[1 7 8]
 [3 4 9]
 [2 5 6]]
